#!/bin/bash
#SBATCH --job-name=runFoam-V1.12
#SBATCH --partition=debug64c512g
#SBATCH -n 64
#SBATCH --ntasks-per-node=64
#SBATCH --output=%j.out
#SBATCH --error=%j.err


#------------------------------------------------------------------------------
#1. Defining the container to be used
theRepo=/dssg/home/acct-medgm/medgm/00-sif
theContainerBaseName=openfoam
theVersion=9
theProvider=github
theImage=$theRepo/$theContainerBaseName-$theVersion-$theProvider.sif
projectUserDir=/dssg/home/acct-medgm/medgm/projectUserDir-9
#------------------------------------------------------------------------------

theSolver="hisa"

#        runApplication decomposePar
singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage decomposePar

#        runParallel -s parallel renumberMesh -overwrite
singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage renumberMesh -overwrite 

srun --mpi=pmi2 singularity exec -B $projectUserDir:/home/ofuser/OpenFOAM/ofuser-$theVersion $theImage $theSolver -parallel  2>&1 | tee setups.orig/log.trasient1theSolver.$SLURM_JOBID


#------------------------------------------------------------------------------
